In [2]:
import pandas as pd
csv_1 = pd.read_csv("C:\\Users\\iamad\\AI and ML\\data.csv")
csv_1

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [6]:
csv_2 = pd.read_csv("C:\\Users\\iamad\\AI and ML\\data.csv", nrows=3)
csv_2

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0

In [12]:
csv_3 = pd.read_csv("C:\\Users\\iamad\\AI and ML\\data.csv", skiprows = [0,])
csv_3

     60  '2020/12/01'  110  130  409.1
0    60  '2020/12/02'  117  145  479.0
1    60  '2020/12/03'  103  135  340.0
2    45  '2020/12/04'  109  175  282.4
3    45  '2020/12/05'  117  148  406.0
4    60  '2020/12/06'  102  127  300.0
5    60  '2020/12/07'  110  136  374.0
6   450  '2020/12/08'  104  134  253.3
7    30  '2020/12/09'  109  133  195.1
8    60  '2020/12/10'   98  124  269.0
9    60  '2020/12/11'  103  147  329.3
10   60  '2020/12/12'  100  120  250.7
11   60  '2020/12/12'  100  120  250.7
12   60  '2020/12/13'  106  128  345.3
13   60  '2020/12/14'  104  132  379.3
14   60  '2020/12/15'   98  123  275.0
15   60  '2020/12/16'   98  120  215.2
16   60  '2020/12/17'  100  120  300.0
17   45  '2020/12/18'   90  112    NaN
18   60  '2020/12/19'  103  123  323.0
19   45  '2020/12/20'   97  125  243.0
20   60  '2020/12/21'  108  131  364.2
21   45           NaN  100  119  282.0
22   60  '2020/12/23'  130  101  300.0
23   45  '2020/12/24'  105  132  246.0
24   60  '2020/12/25'  102  126  334.5
25   60      20201226  100  120  250.0
26   60  '2020/12/27'   92  118  241.0
27   60  '2020/12/28'  103  132    NaN
28   60  '2020/12/29'  100  132  280.0
29   60  '2020/12/30'  102  129  380.3
30   60  '2020/12/31'   92  115  243.0

In [13]:
csv_4 = pd.read_csv("C:\\Users\\iamad\\AI and ML\\data.csv", index_col = "Date")
csv_4

              Duration  Pulse  Maxpulse  Calories
Date
'2020/12/01'        60    110       130     409.1
'2020/12/02'        60    117       145     479.0
'2020/12/03'        60    103       135     340.0
'2020/12/04'        45    109       175     282.4
'2020/12/05'        45    117       148     406.0
'2020/12/06'        60    102       127     300.0
'2020/12/07'        60    110       136     374.0
'2020/12/08'       450    104       134     253.3
'2020/12/09'        30    109       133     195.1
'2020/12/10'        60     98       124     269.0
'2020/12/11'        60    103       147     329.3
'2020/12/12'        60    100       120     250.7
'2020/12/12'        60    100       120     250.7
'2020/12/13'        60    106       128     345.3
'2020/12/14'        60    104       132     379.3
'2020/12/15'        60     98       123     275.0
'2020/12/16'        60     98       120     215.2
'2020/12/17'        60    100       120     300.0
'2020/12/18'        45     90       112       NaN
'2020/12/19'        60    103       123     323.0
'2020/12/20'        45     97       125     243.0
'2020/12/21'        60    108       131     364.2
NaN                 45    100       119     282.0
'2020/12/23'        60    130       101     300.0
'2020/12/24'        45    105       132     246.0
'2020/12/25'        60    102       126     334.5
20201226            60    100       120     250.0
'2020/12/27'        60     92       118     241.0
'2020/12/28'        60    103       132       NaN
'2020/12/29'        60    100       132     280.0
'2020/12/30'        60    102       129     380.3
'2020/12/31'        60     92       115     243.0

In [14]:
csv_5 = pd.read_csv("C:\\Users\\iamad\\AI and ML\\data.csv", header = 2)
csv_5

     60  '2020/12/02'  117  145  479.0
0    60  '2020/12/03'  103  135  340.0
1    45  '2020/12/04'  109  175  282.4
2    45  '2020/12/05'  117  148  406.0
3    60  '2020/12/06'  102  127  300.0
4    60  '2020/12/07'  110  136  374.0
5   450  '2020/12/08'  104  134  253.3
6    30  '2020/12/09'  109  133  195.1
7    60  '2020/12/10'   98  124  269.0
8    60  '2020/12/11'  103  147  329.3
9    60  '2020/12/12'  100  120  250.7
10   60  '2020/12/12'  100  120  250.7
11   60  '2020/12/13'  106  128  345.3
12   60  '2020/12/14'  104  132  379.3
13   60  '2020/12/15'   98  123  275.0
14   60  '2020/12/16'   98  120  215.2
15   60  '2020/12/17'  100  120  300.0
16   45  '2020/12/18'   90  112    NaN
17   60  '2020/12/19'  103  123  323.0
18   45  '2020/12/20'   97  125  243.0
19   60  '2020/12/21'  108  131  364.2
20   45           NaN  100  119  282.0
21   60  '2020/12/23'  130  101  300.0
22   45  '2020/12/24'  105  132  246.0
23   60  '2020/12/25'  102  126  334.5
24   60      20201226  100  120  250.0
25   60  '2020/12/27'   92  118  241.0
26   60  '2020/12/28'  103  132    NaN
27   60  '2020/12/29'  100  132  280.0
28   60  '2020/12/30'  102  129  380.3
29   60  '2020/12/31'   92  115  243.0

In [15]:
csv_6 = pd.read_csv("C:\\Users\\iamad\\AI and ML\\data.csv", names = ["A","B","C","D","E"])
csv_6

           A             B      C         D         E
0   Duration          Date  Pulse  Maxpulse  Calories
1         60  '2020/12/01'    110       130     409.1
2         60  '2020/12/02'    117       145     479.0
3         60  '2020/12/03'    103       135     340.0
4         45  '2020/12/04'    109       175     282.4
5         45  '2020/12/05'    117       148     406.0
6         60  '2020/12/06'    102       127     300.0
7         60  '2020/12/07'    110       136     374.0
8        450  '2020/12/08'    104       134     253.3
9         30  '2020/12/09'    109       133     195.1
10        60  '2020/12/10'     98       124     269.0
11        60  '2020/12/11'    103       147     329.3
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/12'    100       120     250.7
14        60  '2020/12/13'    106       128     345.3
15        60  '2020/12/14'    104       132     379.3
16        60  '2020/12/15'     98       123     275.0
17        60  '2020/12/16'     98       120     215.2
18        60  '2020/12/17'    100       120     300.0
19        45  '2020/12/18'     90       112       NaN
20        60  '2020/12/19'    103       123     323.0
21        45  '2020/12/20'     97       125     243.0
22        60  '2020/12/21'    108       131     364.2
23        45           NaN    100       119     282.0
24        60  '2020/12/23'    130       101     300.0
25        45  '2020/12/24'    105       132     246.0
26        60  '2020/12/25'    102       126     334.5
27        60      20201226    100       120     250.0
28        60  '2020/12/27'     92       118     241.0
29        60  '2020/12/28'    103       132       NaN
30        60  '2020/12/29'    100       132     280.0
31        60  '2020/12/30'    102       129     380.3
32        60  '2020/12/31'     92       115     243.0